import { describe, it, expect } from 'vitest';
import capabilitiesJson from './__fixtures__/capabilities.json';
import type { Capabilities } from './weather';

// The fixture is generated by TestCapabilities_GoldenFixture in
// internal/httpserver/capabilities_fixture_test.go. This assignment is the
// cross-language pin: a key renamed or dropped on the Go side changes the
// fixture and fails this typecheck, and a key renamed in Capabilities fails
// it against an unchanged fixture. Issue #149 tracks replacing this with
// real generation across the whole Contract C surface.
describe('Capabilities wire contract', () => {
  it('matches the JSON the Go server emits', () => {
    const fixture: Capabilities = capabilitiesJson;

    expect(Object.keys(fixture).sort()).toEqual(['almanac', 'forecast', 'radar']);
    expect(fixture.forecast).toBe(false);
    expect(fixture.radar).toBe(false);
    expect(fixture.almanac).toBe(false);
  });
});
